accounts/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
import accounts.views


urlpatterns = (
    url(r'^register', accounts.views.register, name='register'),
    url(r'^login', accounts.views.user_login, name='user_login'),
    url(r'^logout', accounts.views.user_logout, name='user_logout'),
    # url(r'^$', login_required(RedirectView.as_view(url=reverse_lazy('account_detail'), permanent=False))),
    url(r'^create/$', accounts.views.CreateUser.as_view(), name='account_create'),
    url(r'^detail/$', login_required(accounts.views.DetailUser.as_view()), name='account_detail'),
    url(r'^update/$', login_required(accounts.views.UpdateUser.as_view()), name='account_update'),
)

urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='landing.html'), name='landing'),
    url(r'^admin/docs/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.core.mail import send_mail

from django.db import models
from django.core import validators
from django.conf import settings

from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin


class User(AbstractBaseUser, PermissionsMixin):
    """
    Users within the Django authentication system are represented by this
    model.

    Username, password and email are required. Other fields are optional.
    """

    objects = UserManager()
    username = models.CharField(
        _('username'),
        max_length=30,
        unique=True,
        help_text=_('Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[validators.RegexValidator(r'^[\w.@+-]+$', _('Enter a valid username.'), 'invalid')]
    )

    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    email = models.EmailField(_('email address'), blank=True)

    photo = models.ImageField(upload_to='users', blank=True, null=True)

    is_staff = models.BooleanField(
        _('staff status'), default=False,
        help_text=_('Designates whether the user can log into this admin site.'))
    is_active = models.BooleanField(
        _('active'), default=True,
        help_text=_('Designates whether this user should be treated as '
                    'active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    @property
    def full_name(self):
        return self.get_full_name()

    @staticmethod
    def get_absolute_url():
        return settings.LOGIN_REDIRECT_URL

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Returns the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email], **kwargs)

accounts/forms.py
import django.contrib.auth.models
from django import forms

from django.utils.translation import ugettext as _

from accounts.models import User


class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label=_('Password'), widget=forms.PasswordInput)
    password2 = forms.CharField(label=_('Password confirmation'), widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'photo')


class RegistrationForm(django.forms.ModelForm):
    password = django.forms.CharField(widget=django.forms.PasswordInput())

    class Meta:
        model = django.contrib.auth.models.User
        fields = ('username', 'email', 'password')

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].required = True
            self.fields[field].widget.attrs.update({'class': 'form-control', 'placeholder': field})

accounts/views.py
import django.contrib.auth
import django.contrib.auth.decorators
import django.contrib.messages
import django.http
import django.shortcuts
import django.template
from django.contrib.auth import get_user_model
from django.views.generic import DetailView, UpdateView, CreateView
from accounts.forms import UserCreationForm, UserUpdateForm

from .forms import RegistrationForm


def register(request):
    context = django.template.RequestContext(request)
    registered = False

    if request.method == 'POST':
        user_form = RegistrationForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
        else:
            django.contrib.messages.info(request, 'Please correct errors below.')
    else:
        user_form = RegistrationForm()

    return django.shortcuts.render_to_response(
        'accounts/register.html', {'user_form': user_form, 'registered': registered}, context)


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = django.contrib.auth.authenticate(username=username, password=password)
        if user:
            if user.is_active:
                django.contrib.auth.login(request, user)
                return django.http.HttpResponseRedirect('/')
            else:
                django.contrib.messages.info(request, 'Your account is disabled.')
        else:
            django.contrib.messages.info(request, 'Invalid Credentials.')

    return django.shortcuts.render(request, 'accounts/login.html', {})


@django.contrib.auth.decorators.login_required
def user_logout(request):
    django.contrib.auth.logout(request)
    return django.http.HttpResponseRedirect('/')


User = get_user_model()


class DetailUser(DetailView):
    model = User

    def get_object(self, queryset=None):
        return self.request.user


class CreateUser(CreateView):
    model = User
    form_class = UserCreationForm


class UpdateUser(UpdateView):
    model = User
    form_class = UserUpdateForm

    def get_object(self, queryset=None):
        return self.request.user

templates/accounts/accounts.html
<div class="container">
  <div class="row">
  	<div class="col-md-6">

          <form class="form-horizontal" action="" method="POST">
          <fieldset>
            <div id="legend">
              <legend class="">Register</legend>
            </div>
            <div class="control-group">
              <label class="control-label" for="username">Username</label>
              <div class="controls">
                <input type="text" id="username" name="username" placeholder="" class="form-control input-lg">
                <p class="help-block">Username can contain any letters or numbers, without spaces</p>
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="email">E-mail</label>
              <div class="controls">
                <input type="email" id="email" name="email" placeholder="" class="form-control input-lg">
                <p class="help-block">Please provide your E-mail</p>
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="password">Password</label>
              <div class="controls">
                <input type="password" id="password" name="password" placeholder="" class="form-control input-lg">
                <p class="help-block">Password should be at least 6 characters</p>
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="password_confirm">Password (Confirm)</label>
              <div class="controls">
                <input type="password" id="password_confirm" name="password_confirm" placeholder="" class="form-control input-lg">
                <p class="help-block">Please confirm password</p>
              </div>
            </div>

            <div class="control-group">
              <div class="controls">
                <button class="btn btn-success">Register</button>
              </div>
            </div>
          </fieldset>
        </form>

    </div>
  </div>
</div>

templates/accounts/login.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Login{% endblock %}
{% block content %}
    <div class="container col-lg-offset-3 col-lg-9" id="login-container">
        <div class="jumbotron" id="login-jumbotron">
            <h2 class="no-margin-t">Login</h2>
            {% if messages %}
                <ul class="list-group">
                    {% for message in messages %}
                        <li class="list-group-item list-group-item-action list-group-item-warning">{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <form method="post">
                {% csrf_token %}
                <div class="form-group row user-form-field {% if messages %} has-error{% endif %}">
                    <div class="col-sm-offset-1 col-sm-10">
                        <input type="text"
                               name="username"
                               value=""
                               class="form-control"
                               placeholder="Username"/>
                    </div>
                </div>
                <div class="form-group row user-form-field {% if messages %} has-error{% endif %}">
                    <div class="col-sm-offset-1 col-sm-10">
                        <input type="password"
                               name="password"
                               value=""
                               class="form-control"
                               placeholder="Password"/>

                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-offset-1 col-sm-10">
                        <button type="submit" class="btn btn-primary btn-lg btn-block">Login</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/accounts/register.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Register{% endblock %}
{% block content %}
    {% if registered %}
        <strong>Thank you for registering!</strong>
        <a href="{% url 'accounts:user_login' %}">Login</a><br/>
    {% else %}
        <div class="container col-lg-offset-3 col-lg-9" id="register-container">
            <div class="jumbotron" id="register-jumbotron">
                <h2 class="no-margin-t">Create Account</h2>
                {% if messages %}
                    <ul class="list-group">
                        {% for message in messages %}
                            <li class="list-group-item list-group-item-action list-group-item-warning">
                                {{ message }}
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <form method="post">
                    {% csrf_token %}
                    {% for field in user_form %}
                        {% for error in field.errors %}
                            {{ error }}
                        {% endfor %}
                        <div class="form-group row user-form-field {% if field.errors %}has-error{% endif %}">
                            <div class="col-sm-offset-1 col-sm-10">
                                {{ field }}
                            </div>
                        </div>
                    {% endfor %}
                    <div class="form-group row">
                        <div class="col-sm-offset-1 col-sm-10">
                            <button type="submit" class="btn btn-primary btn-lg btn-block">Create</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/accounts/user_detail.html
{% extends 'layouts/base.html' %}
{% load i18n thumbnail %}

{% block body %}

    <h2>Welcome back {{ user }}!</h2>

    {% thumbnail user.photo "100x100" crop="center" as im %}
        <img src="{{ im.url }}" alt="{{ user }} Photo" width="{{ im.width }}" height="{{ im.height }}"/>
    {% empty %}
        <a href="{% url 'account_update' %}">{% trans 'Edit your profile to have a user photo.' %}</a>
    {% endthumbnail %}

    <ul>
        <li><a href="{% url 'account_update' %}">{% trans 'Edit your Account' %}</a></li>
        <li><a href="{% url 'password_change' %}">{% trans 'Change your Password' %}</a></li>
    </ul>

{% endblock %}

templates/accounts/user_form.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

    <h2>Welcome!</h2>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {% if object %}
            <input type="submit" value="{% trans 'Update' %}"/>
        {% else %}
            <input type="submit" value="{% trans 'Sign up' %}"/>
        {% endif %}
    </form>

{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>
        {% block title %}Sales Farm{% endblock %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <script type="text/javascript" src="{% static 'js/jquery-3.1.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}"/>
</head>
<body>
{% block nav_bar %}
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Brand</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                    <li><a href="#">Link</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">Dropdown <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">Account<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url "accounts:account_detail" %}">Settings</a></li>
                                <li><a href="{% url "accounts:user_logout" %}">Log Out</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{% url "accounts:user_login" %}">Login</a></li>
                        <li><a href="{% url "accounts:account_create" %}">Sign Up</a></li>
                    {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
{% endblock %}
{% block content %}{% endblock %}
{% block page_css %}{% endblock %}
{% block page_js %}{% endblock %}
</body>
</html>

templates/landing.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Industry Stats{% endblock %}
{% block styles %}
    {{ block.super }}
    <style>
        html,
        body {
            height: 100%;
            color: #fff;
            background-image: url('{% static 'dist/images/map-unsplash.jpg' %}');
            background-size: cover;
            background-position: center center;
            background-repeat: no-repeat;
            background-color: #000;
            text-shadow: 0 0 2px rgba(0, 0, 0, 0.8);
        }

        .site-wrapper {
            display: table;
            width: 100%;
            height: 100%; /* For at least Firefox */
            min-height: 100%;
            -webkit-box-shadow: inset 0 0 600px rgba(0, 0, 0, .9);
            box-shadow: inset 0 0 600px rgba(0, 0, 0, .9);
        }

        h3 small {
            color: #fff;
        }

        a {
            color: #fff;
            font-weight: 800;
            text-decoration: none;
        }

        a:hover, a:visited {
            color: #fff;
        }

        .site-wrapper-inner {
            display: table-cell;
            vertical-align: top;
        }

        .jumbotron {
            margin-right: auto;
            margin-left: auto;
            background: transparent;
            padding: 30px;
        }

        footer {
            position: absolute;
            bottom: 0;
            height: 60px;
        }
    </style>
{% endblock %}
{% block body %}
{% endblock %}